"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CHI_B_RNF_rtl = exports.CHI_B_RND_rtl = exports.CHI_A_SNI_rtl = exports.CHI_A_SNF_rtl = exports.CHI_A_RNI_rtl = exports.CHI_A_RNF_rtl = exports.CHI_A_RND_rtl = exports.AXI5_Stream_rtl = exports.AXI5_Lite_rtl2 = exports.AXI5_Lite_rtl = exports.AXI5_rtl2 = exports.AXI5_rtl = exports.ATB_rtl3 = exports.APB5_rtl = exports.AHB5Target_rtl = exports.AHB5Initiator_rtl = exports.ACE5_LiteDVM_rtl2 = exports.ACE5_LiteDVM_rtl = exports.ACE5_LiteACP_rtl3 = exports.ACE5_LiteACP_rtl2 = exports.ACE5_LiteACP_rtl = exports.ACE5_Lite_rtl2 = exports.ACE5_Lite_rtl = exports.ACE5_rtl = exports.Q_Channel_rtl = exports.P_Channel_rtl = exports.AXI4_WO_rtl = exports.AXI4_RO_rtl = exports.AXI4Stream_rtl = exports.AXI4_Lite_rtl = exports.AXI4 = exports.ATB_rtl2 = exports.APB4_rtl = exports.ACP_rtl = exports.ACE_Lite_WO_rtl = exports.ACE_Lite_RO_rtl = exports.ACE_Lite_rtl = exports.ACE_rtl = exports.LPI_rtl3 = exports.LPI_rtl2 = exports.LPI_rtl = exports.AXI_WO_rtl = exports.AXI_RO_rtl = exports.AXI = exports.ATB = exports.APB = exports.AHBLiteTarget = exports.AHBLiteInitiator = exports.AHBLite = exports.AHB = void 0;
exports.LTI_rtl2 = exports.LTI_rtl = exports.GFB_rtl = exports.CXS_rtl = exports.CHI_G_SNI_rtl = exports.CHI_G_SNF_rtl = exports.CHI_G_RNI_rtl = exports.CHI_G_RNF_rtl = exports.CHI_G_RND_rtl = exports.CHI_F_SNI_rtl = exports.CHI_F_SNF_rtl = exports.CHI_F_RNI_rtl = exports.CHI_F_RNF_rtl = exports.CHI_F_RND_rtl = exports.CHI_E_SNI_rtl = exports.CHI_E_SNF_rtl = exports.CHI_E_RNI_rtl = exports.CHI_E_RNF_rtl = exports.CHI_E_RND_rtl = exports.CHI_D_SNI_rtl = exports.CHI_D_SNF_rtl = exports.CHI_D_RNI_rtl = exports.CHI_D_RNF_rtl = exports.CHI_D_RND_rtl = exports.CHI_C_SNI_rtl = exports.CHI_C_SNF_rtl = exports.CHI_C_RNI_rtl = exports.CHI_C_RNF_rtl = exports.CHI_C_RND_rtl = exports.CHI_B_SNI_rtl = exports.CHI_B_SNF_rtl = exports.CHI_B_RNI_rtl = void 0;
// Auto_generated index file
var AHB_1 = require("tssv/lib/interfaces/AMBA/AMBA2/AHB/r3p0_1/AHB");
Object.defineProperty(exports, "AHB", { enumerable: true, get: function () { return AHB_1.AHB; } });
var AHBLite_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AHBLite/r2p0_0/AHBLite");
Object.defineProperty(exports, "AHBLite", { enumerable: true, get: function () { return AHBLite_1.AHBLite; } });
var AHBLiteInitiator_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AHBLiteInitiator/r2p0_0/AHBLiteInitiator");
Object.defineProperty(exports, "AHBLiteInitiator", { enumerable: true, get: function () { return AHBLiteInitiator_1.AHBLiteInitiator; } });
var AHBLiteTarget_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AHBLiteTarget/r2p0_0/AHBLiteTarget");
Object.defineProperty(exports, "AHBLiteTarget", { enumerable: true, get: function () { return AHBLiteTarget_1.AHBLiteTarget; } });
var APB_1 = require("tssv/lib/interfaces/AMBA/AMBA3/APB/r2p0_0/APB");
Object.defineProperty(exports, "APB", { enumerable: true, get: function () { return APB_1.APB; } });
var ATB_1 = require("tssv/lib/interfaces/AMBA/AMBA3/ATB/r2p0_0/ATB"); //
Object.defineProperty(exports, "ATB", { enumerable: true, get: function () { return ATB_1.ATB; } });
var AXI_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AXI/r2p0_0/AXI");
Object.defineProperty(exports, "AXI", { enumerable: true, get: function () { return AXI_1.AXI; } });
var AXI_RO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AXI_RO/r2p0_0/AXI_RO_rtl");
Object.defineProperty(exports, "AXI_RO_rtl", { enumerable: true, get: function () { return AXI_RO_rtl_1.AXI_RO_rtl; } });
var AXI_WO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA3/AXI_WO/r2p0_0/AXI_WO_rtl");
Object.defineProperty(exports, "AXI_WO_rtl", { enumerable: true, get: function () { return AXI_WO_rtl_1.AXI_WO_rtl; } });
var LPI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA3/LPI/r2p0_0/LPI_rtl");
Object.defineProperty(exports, "LPI_rtl", { enumerable: true, get: function () { return LPI_rtl_1.LPI_rtl; } });
var LPI_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA3/LPI/r2p1_0/LPI_rtl"); //
Object.defineProperty(exports, "LPI_rtl2", { enumerable: true, get: function () { return LPI_rtl_2.LPI_rtl; } });
var LPI_rtl_3 = require("tssv/lib/interfaces/AMBA/AMBA3/LPI/r3p0_0/LPI_rtl"); //
Object.defineProperty(exports, "LPI_rtl3", { enumerable: true, get: function () { return LPI_rtl_3.LPI_rtl; } });
var ACE_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ACE/r0p0_0/ACE_rtl");
Object.defineProperty(exports, "ACE_rtl", { enumerable: true, get: function () { return ACE_rtl_1.ACE_rtl; } });
var ACE_Lite_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ACE-Lite/r0p0_0/ACE-Lite_rtl");
Object.defineProperty(exports, "ACE_Lite_rtl", { enumerable: true, get: function () { return ACE_Lite_rtl_1.ACE_Lite_rtl; } });
var ACE_Lite_RO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ACE-Lite_RO/r0p0_0/ACE-Lite_RO_rtl");
Object.defineProperty(exports, "ACE_Lite_RO_rtl", { enumerable: true, get: function () { return ACE_Lite_RO_rtl_1.ACE_Lite_RO_rtl; } });
var ACE_Lite_WO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ACE-Lite_WO/r0p0_0/ACE-Lite_WO_rtl");
Object.defineProperty(exports, "ACE_Lite_WO_rtl", { enumerable: true, get: function () { return ACE_Lite_WO_rtl_1.ACE_Lite_WO_rtl; } });
var ACP_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ACP/r0p0_0/ACP_rtl");
Object.defineProperty(exports, "ACP_rtl", { enumerable: true, get: function () { return ACP_rtl_1.ACP_rtl; } });
var APB4_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/APB4/r0p0_0/APB4_rtl");
Object.defineProperty(exports, "APB4_rtl", { enumerable: true, get: function () { return APB4_rtl_1.APB4_rtl; } });
var ATB_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/ATB/r0p0_0/ATB_rtl"); //
Object.defineProperty(exports, "ATB_rtl2", { enumerable: true, get: function () { return ATB_rtl_1.ATB_rtl; } });
var AXI4_1 = require("tssv/lib/interfaces/AMBA/AMBA4/AXI4/r0p0_0/AXI4");
Object.defineProperty(exports, "AXI4", { enumerable: true, get: function () { return AXI4_1.AXI4; } });
var AXI4_Lite_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/AXI4-Lite/r0p0_0/AXI4-Lite_rtl");
Object.defineProperty(exports, "AXI4_Lite_rtl", { enumerable: true, get: function () { return AXI4_Lite_rtl_1.AXI4_Lite_rtl; } });
var AXI4Stream_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/AXI4Stream/r0p0_1/AXI4Stream_rtl");
Object.defineProperty(exports, "AXI4Stream_rtl", { enumerable: true, get: function () { return AXI4Stream_rtl_1.AXI4Stream_rtl; } });
var AXI4_RO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/AXI4_RO/r0p0_0/AXI4_RO_rtl");
Object.defineProperty(exports, "AXI4_RO_rtl", { enumerable: true, get: function () { return AXI4_RO_rtl_1.AXI4_RO_rtl; } });
var AXI4_WO_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/AXI4_WO/r0p0_0/AXI4_WO_rtl");
Object.defineProperty(exports, "AXI4_WO_rtl", { enumerable: true, get: function () { return AXI4_WO_rtl_1.AXI4_WO_rtl; } });
var P_Channel_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/P-Channel/r0p0_0/P-Channel_rtl");
Object.defineProperty(exports, "P_Channel_rtl", { enumerable: true, get: function () { return P_Channel_rtl_1.P_Channel_rtl; } });
var Q_Channel_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA4/Q-Channel/r0p0_0/Q-Channel_rtl");
Object.defineProperty(exports, "Q_Channel_rtl", { enumerable: true, get: function () { return Q_Channel_rtl_1.Q_Channel_rtl; } });
var ACE5_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5/r0p0_0/ACE5_rtl");
Object.defineProperty(exports, "ACE5_rtl", { enumerable: true, get: function () { return ACE5_rtl_1.ACE5_rtl; } });
var ACE5_Lite_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-Lite/r0p0_0/ACE5-Lite_rtl");
Object.defineProperty(exports, "ACE5_Lite_rtl", { enumerable: true, get: function () { return ACE5_Lite_rtl_1.ACE5_Lite_rtl; } });
var ACE5_Lite_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-Lite/r0p2_0/ACE5-Lite_rtl");
Object.defineProperty(exports, "ACE5_Lite_rtl2", { enumerable: true, get: function () { return ACE5_Lite_rtl_2.ACE5_Lite_rtl; } });
var ACE5_LiteACP_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-LiteACP/r0p0_0/ACE5-LiteACP_rtl");
Object.defineProperty(exports, "ACE5_LiteACP_rtl", { enumerable: true, get: function () { return ACE5_LiteACP_rtl_1.ACE5_LiteACP_rtl; } });
var ACE5_LiteACP_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-LiteACP/r0p2_0/ACE5-LiteACP_rtl");
Object.defineProperty(exports, "ACE5_LiteACP_rtl2", { enumerable: true, get: function () { return ACE5_LiteACP_rtl_2.ACE5_LiteACP_rtl; } });
var ACE5_LiteACP_rtl_3 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-LiteACP/r0p3_0/ACE5-LiteACP_rtl");
Object.defineProperty(exports, "ACE5_LiteACP_rtl3", { enumerable: true, get: function () { return ACE5_LiteACP_rtl_3.ACE5_LiteACP_rtl; } });
var ACE5_LiteDVM_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-LiteDVM/r0p0_0/ACE5-LiteDVM_rtl");
Object.defineProperty(exports, "ACE5_LiteDVM_rtl", { enumerable: true, get: function () { return ACE5_LiteDVM_rtl_1.ACE5_LiteDVM_rtl; } });
var ACE5_LiteDVM_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/ACE5-LiteDVM/r0p2_0/ACE5-LiteDVM_rtl");
Object.defineProperty(exports, "ACE5_LiteDVM_rtl2", { enumerable: true, get: function () { return ACE5_LiteDVM_rtl_2.ACE5_LiteDVM_rtl; } });
var AHB5Initiator_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/AHB5Initiator/r0p0_0/AHB5Initiator_rtl");
Object.defineProperty(exports, "AHB5Initiator_rtl", { enumerable: true, get: function () { return AHB5Initiator_rtl_1.AHB5Initiator_rtl; } });
var AHB5Target_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/AHB5Target/r0p0_0/AHB5Target_rtl");
Object.defineProperty(exports, "AHB5Target_rtl", { enumerable: true, get: function () { return AHB5Target_rtl_1.AHB5Target_rtl; } });
var APB5_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/APB5/r0p0_0/APB5_rtl");
Object.defineProperty(exports, "APB5_rtl", { enumerable: true, get: function () { return APB5_rtl_1.APB5_rtl; } });
var ATB_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/ATB/r0p0_0/ATB_rtl");
Object.defineProperty(exports, "ATB_rtl3", { enumerable: true, get: function () { return ATB_rtl_2.ATB_rtl; } });
var AXI5_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/AXI5/r0p0_0/AXI5_rtl");
Object.defineProperty(exports, "AXI5_rtl", { enumerable: true, get: function () { return AXI5_rtl_1.AXI5_rtl; } });
var AXI5_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/AXI5/r0p2_0/AXI5_rtl");
Object.defineProperty(exports, "AXI5_rtl2", { enumerable: true, get: function () { return AXI5_rtl_2.AXI5_rtl; } });
var AXI5_Lite_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/AXI5-Lite/r0p0_0/AXI5-Lite_rtl");
Object.defineProperty(exports, "AXI5_Lite_rtl", { enumerable: true, get: function () { return AXI5_Lite_rtl_1.AXI5_Lite_rtl; } });
var AXI5_Lite_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/AXI5-Lite/r0p2_0/AXI5-Lite_rtl");
Object.defineProperty(exports, "AXI5_Lite_rtl2", { enumerable: true, get: function () { return AXI5_Lite_rtl_2.AXI5_Lite_rtl; } });
var AXI5_Stream_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/AXI5-Stream/r0p0_0/AXI5-Stream_rtl");
Object.defineProperty(exports, "AXI5_Stream_rtl", { enumerable: true, get: function () { return AXI5_Stream_rtl_1.AXI5_Stream_rtl; } });
var CHI_A_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-A-RND/r0p0_0/CHI-A-RND_rtl");
Object.defineProperty(exports, "CHI_A_RND_rtl", { enumerable: true, get: function () { return CHI_A_RND_rtl_1.CHI_A_RND_rtl; } });
var CHI_A_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-A-RNF/r0p0_0/CHI-A-RNF_rtl");
Object.defineProperty(exports, "CHI_A_RNF_rtl", { enumerable: true, get: function () { return CHI_A_RNF_rtl_1.CHI_A_RNF_rtl; } });
var CHI_A_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-A-RNI/r0p0_0/CHI-A-RNI_rtl");
Object.defineProperty(exports, "CHI_A_RNI_rtl", { enumerable: true, get: function () { return CHI_A_RNI_rtl_1.CHI_A_RNI_rtl; } });
var CHI_A_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-A-SNF/r0p0_0/CHI-A-SNF_rtl");
Object.defineProperty(exports, "CHI_A_SNF_rtl", { enumerable: true, get: function () { return CHI_A_SNF_rtl_1.CHI_A_SNF_rtl; } });
var CHI_A_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-A-SNI/r0p0_0/CHI-A-SNI_rtl");
Object.defineProperty(exports, "CHI_A_SNI_rtl", { enumerable: true, get: function () { return CHI_A_SNI_rtl_1.CHI_A_SNI_rtl; } });
var CHI_B_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-B-RND/r0p0_0/CHI-B-RND_rtl");
Object.defineProperty(exports, "CHI_B_RND_rtl", { enumerable: true, get: function () { return CHI_B_RND_rtl_1.CHI_B_RND_rtl; } });
var CHI_B_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-B-RNF/r0p0_0/CHI-B-RNF_rtl");
Object.defineProperty(exports, "CHI_B_RNF_rtl", { enumerable: true, get: function () { return CHI_B_RNF_rtl_1.CHI_B_RNF_rtl; } });
var CHI_B_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-B-RNI/r0p0_0/CHI-B-RNI_rtl");
Object.defineProperty(exports, "CHI_B_RNI_rtl", { enumerable: true, get: function () { return CHI_B_RNI_rtl_1.CHI_B_RNI_rtl; } });
var CHI_B_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-B-SNF/r0p0_0/CHI-B-SNF_rtl");
Object.defineProperty(exports, "CHI_B_SNF_rtl", { enumerable: true, get: function () { return CHI_B_SNF_rtl_1.CHI_B_SNF_rtl; } });
var CHI_B_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-B-SNI/r0p0_0/CHI-B-SNI_rtl");
Object.defineProperty(exports, "CHI_B_SNI_rtl", { enumerable: true, get: function () { return CHI_B_SNI_rtl_1.CHI_B_SNI_rtl; } });
var CHI_C_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-C-RND/r0p0_0/CHI-C-RND_rtl");
Object.defineProperty(exports, "CHI_C_RND_rtl", { enumerable: true, get: function () { return CHI_C_RND_rtl_1.CHI_C_RND_rtl; } });
var CHI_C_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-C-RNF/r0p0_0/CHI-C-RNF_rtl");
Object.defineProperty(exports, "CHI_C_RNF_rtl", { enumerable: true, get: function () { return CHI_C_RNF_rtl_1.CHI_C_RNF_rtl; } });
var CHI_C_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-C-RNI/r0p0_0/CHI-C-RNI_rtl");
Object.defineProperty(exports, "CHI_C_RNI_rtl", { enumerable: true, get: function () { return CHI_C_RNI_rtl_1.CHI_C_RNI_rtl; } });
var CHI_C_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-C-SNF/r0p0_0/CHI-C-SNF_rtl");
Object.defineProperty(exports, "CHI_C_SNF_rtl", { enumerable: true, get: function () { return CHI_C_SNF_rtl_1.CHI_C_SNF_rtl; } });
var CHI_C_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-C-SNI/r0p0_0/CHI-C-SNI_rtl");
Object.defineProperty(exports, "CHI_C_SNI_rtl", { enumerable: true, get: function () { return CHI_C_SNI_rtl_1.CHI_C_SNI_rtl; } });
var CHI_D_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-D-RND/r0p0_0/CHI-D-RND_rtl");
Object.defineProperty(exports, "CHI_D_RND_rtl", { enumerable: true, get: function () { return CHI_D_RND_rtl_1.CHI_D_RND_rtl; } });
var CHI_D_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-D-RNF/r0p0_0/CHI-D-RNF_rtl");
Object.defineProperty(exports, "CHI_D_RNF_rtl", { enumerable: true, get: function () { return CHI_D_RNF_rtl_1.CHI_D_RNF_rtl; } });
var CHI_D_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-D-RNI/r0p0_0/CHI-D-RNI_rtl");
Object.defineProperty(exports, "CHI_D_RNI_rtl", { enumerable: true, get: function () { return CHI_D_RNI_rtl_1.CHI_D_RNI_rtl; } });
var CHI_D_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-D-SNF/r0p0_0/CHI-D-SNF_rtl");
Object.defineProperty(exports, "CHI_D_SNF_rtl", { enumerable: true, get: function () { return CHI_D_SNF_rtl_1.CHI_D_SNF_rtl; } });
var CHI_D_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-D-SNI/r0p0_0/CHI-D-SNI_rtl");
Object.defineProperty(exports, "CHI_D_SNI_rtl", { enumerable: true, get: function () { return CHI_D_SNI_rtl_1.CHI_D_SNI_rtl; } });
var CHI_E_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-E-RND/r0p0_0/CHI-E-RND_rtl");
Object.defineProperty(exports, "CHI_E_RND_rtl", { enumerable: true, get: function () { return CHI_E_RND_rtl_1.CHI_E_RND_rtl; } });
var CHI_E_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-E-RNF/r0p0_0/CHI-E-RNF_rtl");
Object.defineProperty(exports, "CHI_E_RNF_rtl", { enumerable: true, get: function () { return CHI_E_RNF_rtl_1.CHI_E_RNF_rtl; } });
var CHI_E_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-E-RNI/r0p0_0/CHI-E-RNI_rtl");
Object.defineProperty(exports, "CHI_E_RNI_rtl", { enumerable: true, get: function () { return CHI_E_RNI_rtl_1.CHI_E_RNI_rtl; } });
var CHI_E_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-E-SNF/r0p0_0/CHI-E-SNF_rtl");
Object.defineProperty(exports, "CHI_E_SNF_rtl", { enumerable: true, get: function () { return CHI_E_SNF_rtl_1.CHI_E_SNF_rtl; } });
var CHI_E_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-E-SNI/r0p0_0/CHI-E-SNI_rtl");
Object.defineProperty(exports, "CHI_E_SNI_rtl", { enumerable: true, get: function () { return CHI_E_SNI_rtl_1.CHI_E_SNI_rtl; } });
var CHI_F_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-F-RND/r0p0_0/CHI-F-RND_rtl");
Object.defineProperty(exports, "CHI_F_RND_rtl", { enumerable: true, get: function () { return CHI_F_RND_rtl_1.CHI_F_RND_rtl; } });
var CHI_F_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-F-RNF/r0p0_0/CHI-F-RNF_rtl");
Object.defineProperty(exports, "CHI_F_RNF_rtl", { enumerable: true, get: function () { return CHI_F_RNF_rtl_1.CHI_F_RNF_rtl; } });
var CHI_F_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-F-RNI/r0p0_0/CHI-F-RNI_rtl");
Object.defineProperty(exports, "CHI_F_RNI_rtl", { enumerable: true, get: function () { return CHI_F_RNI_rtl_1.CHI_F_RNI_rtl; } });
var CHI_F_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-F-SNF/r0p0_0/CHI-F-SNF_rtl");
Object.defineProperty(exports, "CHI_F_SNF_rtl", { enumerable: true, get: function () { return CHI_F_SNF_rtl_1.CHI_F_SNF_rtl; } });
var CHI_F_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-F-SNI/r0p0_0/CHI-F-SNI_rtl");
Object.defineProperty(exports, "CHI_F_SNI_rtl", { enumerable: true, get: function () { return CHI_F_SNI_rtl_1.CHI_F_SNI_rtl; } });
var CHI_G_RND_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-G-RND/r0p0_0/CHI-G-RND_rtl");
Object.defineProperty(exports, "CHI_G_RND_rtl", { enumerable: true, get: function () { return CHI_G_RND_rtl_1.CHI_G_RND_rtl; } });
var CHI_G_RNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-G-RNF/r0p0_0/CHI-G-RNF_rtl");
Object.defineProperty(exports, "CHI_G_RNF_rtl", { enumerable: true, get: function () { return CHI_G_RNF_rtl_1.CHI_G_RNF_rtl; } });
var CHI_G_RNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-G-RNI/r0p0_0/CHI-G-RNI_rtl");
Object.defineProperty(exports, "CHI_G_RNI_rtl", { enumerable: true, get: function () { return CHI_G_RNI_rtl_1.CHI_G_RNI_rtl; } });
var CHI_G_SNF_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-G-SNF/r0p0_0/CHI-G-SNF_rtl");
Object.defineProperty(exports, "CHI_G_SNF_rtl", { enumerable: true, get: function () { return CHI_G_SNF_rtl_1.CHI_G_SNF_rtl; } });
var CHI_G_SNI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CHI-G-SNI/r0p0_0/CHI-G-SNI_rtl");
Object.defineProperty(exports, "CHI_G_SNI_rtl", { enumerable: true, get: function () { return CHI_G_SNI_rtl_1.CHI_G_SNI_rtl; } });
var CXS_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/CXS/r0p0_0/CXS_rtl");
Object.defineProperty(exports, "CXS_rtl", { enumerable: true, get: function () { return CXS_rtl_1.CXS_rtl; } });
var GFB_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/GFB/r0p0_0/GFB_rtl");
Object.defineProperty(exports, "GFB_rtl", { enumerable: true, get: function () { return GFB_rtl_1.GFB_rtl; } });
var LTI_rtl_1 = require("tssv/lib/interfaces/AMBA/AMBA5/LTI/r0p0_0/LTI_rtl");
Object.defineProperty(exports, "LTI_rtl", { enumerable: true, get: function () { return LTI_rtl_1.LTI_rtl; } });
var LTI_rtl_2 = require("tssv/lib/interfaces/AMBA/AMBA5/LTI/r0p1_0/LTI_rtl");
Object.defineProperty(exports, "LTI_rtl2", { enumerable: true, get: function () { return LTI_rtl_2.LTI_rtl; } });
